FROM quay.io/keycloak/keycloak:18.0.2-legacy
LABEL MAINTAINER="Villanova <dev@villanova.com>"
ARG VERSION
LABEL name="Villanova Keycloak" \
      vendor="Villanova" \
      version="v${VERSION}" \
      release="0.9" \
      summary="Keycloak with Villanova's themes and extensions." \
      description="This is container hosts Keycloak along with themes created for Villanova."
COPY LICENSE /licences/villanova-lgpl.txt

COPY themes /opt/jboss/keycloak/themes
COPY --chown=jboss:root cli /opt/jboss/tools/cli/
COPY --chown=jboss:root jboss-tools/standalone-configuration.cli /opt/jboss/tools/cli/standalone-configuration.cli
COPY --chown=jboss:root jboss-tools/standalone-ha-configuration.cli /opt/jboss/tools/cli/standalone-ha-configuration.cli

ARG ORACLE_JDBC_DRIVER_VERSION=23.2.0.0
RUN export KEYCLOAK_HTTP_PORT=8080 && \
      cd  /opt/jboss/keycloak/modules/system/layers/base/com/oracle/jdbc/main/ && \
      mkdir driver && \
      curl https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/${ORACLE_JDBC_DRIVER_VERSION}/ojdbc8-${ORACLE_JDBC_DRIVER_VERSION}.jar -o driver/ojdbc.jar

ENV KEYCLOAK_DEFAULT_THEME="villanova" \
    KEYCLOAK_HOME="/opt/jboss/keycloak" \
    HOME="/home/jboss"
    
ENV JGROUPS_DISCOVERY_PROTOCOL="dns.DNS_PING" \
    JGROUPS_DISCOVERY_PROPERTIES="dns_query=keycloak-headless" \
    CACHE_OWNERS_COUNT="2" \
    CACHE_OWNERS_AUTH_SESSIONS_COUNT="2"

USER root
RUN mkdir -p "$HOME"; \
    chown jboss:jboss "$HOME"; \
    chmod g+rwx "$HOME" 
USER jboss

EXPOSE 8080
CMD ["-b", "0.0.0.0"]
